[package]
name = "rush"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.41"
colored = "3.0.0"
crossterm = "0.29.0"
sysinfo = "0.35.2"
terminal_size = "0.4.2"
whoami = "1.6.0"
